mutation ClockInMutation($input: ClockInInput!, $vehicleId: ID!) {
  clockIn(input: $input, vehicleId: $vehicleId) {
    shiftEvent {
      id
      eventType
      odometer
      vehicleRange
      gpsLat
      gpsLon
      notes
      shiftAssignment {
        id
        status
        driver {
          id
          fullName
        }
        vehicle {
          id
          licensePlate
          model
        }
      }
    }
    errors {
      message
      field
      code
    }
  }
}
