query VehiclesQuery {
  vehicles {
    ...VehicleFragment
  }
}

fragment VehicleFragment on Vehicle {
  id
  globalId
  make
  model
  licensePlate
  yearOfManufacture
  displayName
  latestOdometer
  latestRange
  telematicsSource
  vehicleImageUrl
  createdAt
  updatedAt
  inUse
}
