mutation CreateRevenueRecordMutation($input: CreateRevenueRecordInput!) {
  createRevenueRecord(input: $input) {
    revenueRecord {
      id
      globalId
      totalRevenue
      totalProfit
      reconciled
      source
      createdAt
      updatedAt
      driver {
        id
        fullName
      }
      shiftAssignment {
        id
        startTime
        endTime
        vehicle {
          id
          displayName
        }
      }
    }
    errors {
      message
      field
      code
    }
  }
}
