mutation UpdateVehicleMutation($input: UpdateVehicleInput!, $vehicleId: ID!) {
  updateVehicle(input: $input, vehicleId: $vehicleId) {
    vehicle {
      ...VehicleFragment
    }
    errors {
      message
      field
      code
    }
  }
}
