mutation CreateExpenseMutation($input: CreateExpenseInput!) {
  createExpense(input: $input) {
    expense {
      id
      globalId
      amount
      category
      date
      receiptKey
      description
      createdAt
      updatedAt
      user {
        id
        firstName
        lastName
        email
      }
      vehicle {
        id
        displayName
      }
    }
    errors {
      message
      field
      code
    }
  }
}
