query ExpensesQuery(
  $startDate: ISO8601Date
  $endDate: ISO8601Date
  $pagination: PaginationInput!
) {
  expenses(startDate: $startDate, endDate: $endDate, pagination: $pagination) {
    items {
      id
      globalId
      amount
      category
      date
      receiptKey
      description
      createdAt
      updatedAt
      user {
        id
        firstName
        lastName
        email
      }
      vehicle {
        id
        displayName
      }
    }
    pagination {
      currentPage
      firstPage
      lastPage
      nextPage
      pageCount
      pageSize
      prevPage
      totalSize
    }
  }
}
