query TodaysShiftEventsQuery {
  todaysShiftEvents {
    id
    globalId
    eventType
    odometer
    vehicleRange
    gpsLat
    gpsLon
    notes
    createdAt
    shiftAssignment {
      id
      globalId
      driver {
        id
        fullName
      }
      vehicle {
        id
        displayName
        licensePlate
      }
    }
  }
}
