/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "mutation ClockInMutation($input: ClockInInput!, $vehicleId: ID!) {\n  clockIn(input: $input, vehicleId: $vehicleId) {\n    shiftEvent {\n      id\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": typeof types.ClockInMutationDocument,
    "query VehiclesQuery {\n  vehicles {\n    ...VehicleFragment\n  }\n}\n\nfragment VehicleFragment on Vehicle {\n  id\n  globalId\n  make\n  model\n  licensePlate\n  yearOfManufacture\n  displayName\n  latestOdometer\n  latestRange\n  telematicsSource\n  vehicleImageUrl\n  createdAt\n  updatedAt\n  inUse\n}": typeof types.VehiclesQueryDocument,
    "mutation ClockOutMutation($input: ClockOutInput!) {\n  clockOut(input: $input) {\n    shiftEvent {\n      id\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": typeof types.ClockOutMutationDocument,
    "query CurrentShiftQuery {\n  currentShift {\n    ...CurrentShiftFragment\n  }\n}\n\nfragment CurrentShiftFragment on ShiftAssignment {\n  id\n  status\n  city\n  startTime\n  endTime\n  driver {\n    id\n    fullName\n    email\n  }\n  vehicle {\n    id\n    licensePlate\n    model\n    yearOfManufacture\n    latestOdometer\n    latestRange\n  }\n  shiftEvents {\n    id\n    eventType\n    odometer\n    vehicleRange\n    gpsLat\n    gpsLon\n    notes\n    createdAt\n  }\n}": typeof types.CurrentShiftQueryDocument,
    "mutation CreateExpenseMutation($input: CreateExpenseInput!) {\n  createExpense(input: $input) {\n    expense {\n      id\n      globalId\n      amount\n      category\n      date\n      receiptKey\n      createdAt\n      updatedAt\n      user {\n        id\n        firstName\n        lastName\n        email\n      }\n      vehicle {\n        id\n        displayName\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": typeof types.CreateExpenseMutationDocument,
    "query ExpenseStatsQuery($startDate: ISO8601Date, $endDate: ISO8601Date) {\n  expenseStats(startDate: $startDate, endDate: $endDate) {\n    totalAmount\n    count\n    categoryTotals\n  }\n}": typeof types.ExpenseStatsQueryDocument,
    "query ExpensesQuery($startDate: ISO8601Date, $endDate: ISO8601Date, $pagination: PaginationInput!) {\n  expenses(startDate: $startDate, endDate: $endDate, pagination: $pagination) {\n    items {\n      id\n      globalId\n      amount\n      category\n      date\n      receiptKey\n      createdAt\n      updatedAt\n      user {\n        id\n        firstName\n        lastName\n        email\n      }\n      vehicle {\n        id\n        displayName\n      }\n    }\n    pagination {\n      currentPage\n      firstPage\n      lastPage\n      nextPage\n      pageCount\n      pageSize\n      prevPage\n      totalSize\n    }\n  }\n}": typeof types.ExpensesQueryDocument,
    "mutation CreateSessionMutation($input: CreateSessionInput!) {\n  createSession(input: $input) {\n    user {\n      id\n      email\n      firstName\n      lastName\n      fullName\n      driver {\n        id\n        fullName\n      }\n    }\n    authToken {\n      accessToken\n      refreshToken\n      tokenType\n      expiresIn\n    }\n    errors {\n      message\n      code\n      field\n    }\n  }\n}": typeof types.CreateSessionMutationDocument,
    "query MyShiftAssignmentsQuery($startDate: ISO8601Date!, $endDate: ISO8601Date!) {\n  myShiftAssignments(startDate: $startDate, endDate: $endDate) {\n    id\n    city\n    startTime\n    endTime\n    status\n    driver {\n      id\n    }\n    vehicle {\n      id\n      displayName\n    }\n    createdAt\n    updatedAt\n  }\n}": typeof types.MyShiftAssignmentsQueryDocument,
    "query RevenueRecordsQuery($startDate: ISO8601Date, $endDate: ISO8601Date) {\n  revenueRecords(startDate: $startDate, endDate: $endDate) {\n    id\n    globalId\n    totalRevenue\n    totalProfit\n    reconciled\n    source\n    createdAt\n    updatedAt\n    driver {\n      id\n      fullName\n    }\n    shiftAssignment {\n      id\n      startTime\n      endTime\n      city\n      vehicle {\n        id\n        displayName\n      }\n    }\n  }\n}": typeof types.RevenueRecordsQueryDocument,
    "mutation PauseShiftMutation {\n  pauseShift {\n    shiftEvent {\n      id\n      eventType\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": typeof types.PauseShiftMutationDocument,
    "mutation ResumeShiftMutation {\n  resumeShift {\n    shiftEvent {\n      id\n      eventType\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": typeof types.ResumeShiftMutationDocument,
    "query TodayShiftsQuery {\n  todayShifts {\n    id\n    globalId\n    city\n    startTime\n    actualStartTime\n    endTime\n    actualEndTime\n    status\n    driver {\n      id\n      globalId\n      fullName\n      email\n      phoneNumber\n      createdAt\n    }\n    vehicle {\n      id\n      globalId\n      licensePlate\n      model\n      make\n      yearOfManufacture\n      latestOdometer\n      displayName\n      latestRange\n      telematicsSource\n    }\n    shiftEvents {\n      id\n      globalId\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      createdAt\n    }\n    revenueRecords {\n      id\n      globalId\n      totalRevenue\n      totalProfit\n      reconciled\n      createdAt\n    }\n    createdAt\n    updatedAt\n  }\n}": typeof types.TodayShiftsQueryDocument,
    "query TodaysShiftEventsQuery {\n  todaysShiftEvents {\n    id\n    globalId\n    eventType\n    odometer\n    vehicleRange\n    gpsLat\n    gpsLon\n    notes\n    createdAt\n    shiftAssignment {\n      id\n      globalId\n      vehicle {\n        id\n        displayName\n        licensePlate\n      }\n    }\n  }\n}": typeof types.TodaysShiftEventsQueryDocument,
    "mutation UpdateVehicleMutation($input: UpdateVehicleInput!, $vehicleId: ID!) {\n  updateVehicle(input: $input, vehicleId: $vehicleId) {\n    vehicle {\n      ...VehicleFragment\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": typeof types.UpdateVehicleMutationDocument,
};
const documents: Documents = {
    "mutation ClockInMutation($input: ClockInInput!, $vehicleId: ID!) {\n  clockIn(input: $input, vehicleId: $vehicleId) {\n    shiftEvent {\n      id\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": types.ClockInMutationDocument,
    "query VehiclesQuery {\n  vehicles {\n    ...VehicleFragment\n  }\n}\n\nfragment VehicleFragment on Vehicle {\n  id\n  globalId\n  make\n  model\n  licensePlate\n  yearOfManufacture\n  displayName\n  latestOdometer\n  latestRange\n  telematicsSource\n  vehicleImageUrl\n  createdAt\n  updatedAt\n  inUse\n}": types.VehiclesQueryDocument,
    "mutation ClockOutMutation($input: ClockOutInput!) {\n  clockOut(input: $input) {\n    shiftEvent {\n      id\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": types.ClockOutMutationDocument,
    "query CurrentShiftQuery {\n  currentShift {\n    ...CurrentShiftFragment\n  }\n}\n\nfragment CurrentShiftFragment on ShiftAssignment {\n  id\n  status\n  city\n  startTime\n  endTime\n  driver {\n    id\n    fullName\n    email\n  }\n  vehicle {\n    id\n    licensePlate\n    model\n    yearOfManufacture\n    latestOdometer\n    latestRange\n  }\n  shiftEvents {\n    id\n    eventType\n    odometer\n    vehicleRange\n    gpsLat\n    gpsLon\n    notes\n    createdAt\n  }\n}": types.CurrentShiftQueryDocument,
    "mutation CreateExpenseMutation($input: CreateExpenseInput!) {\n  createExpense(input: $input) {\n    expense {\n      id\n      globalId\n      amount\n      category\n      date\n      receiptKey\n      createdAt\n      updatedAt\n      user {\n        id\n        firstName\n        lastName\n        email\n      }\n      vehicle {\n        id\n        displayName\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": types.CreateExpenseMutationDocument,
    "query ExpenseStatsQuery($startDate: ISO8601Date, $endDate: ISO8601Date) {\n  expenseStats(startDate: $startDate, endDate: $endDate) {\n    totalAmount\n    count\n    categoryTotals\n  }\n}": types.ExpenseStatsQueryDocument,
    "query ExpensesQuery($startDate: ISO8601Date, $endDate: ISO8601Date, $pagination: PaginationInput!) {\n  expenses(startDate: $startDate, endDate: $endDate, pagination: $pagination) {\n    items {\n      id\n      globalId\n      amount\n      category\n      date\n      receiptKey\n      createdAt\n      updatedAt\n      user {\n        id\n        firstName\n        lastName\n        email\n      }\n      vehicle {\n        id\n        displayName\n      }\n    }\n    pagination {\n      currentPage\n      firstPage\n      lastPage\n      nextPage\n      pageCount\n      pageSize\n      prevPage\n      totalSize\n    }\n  }\n}": types.ExpensesQueryDocument,
    "mutation CreateSessionMutation($input: CreateSessionInput!) {\n  createSession(input: $input) {\n    user {\n      id\n      email\n      firstName\n      lastName\n      fullName\n      driver {\n        id\n        fullName\n      }\n    }\n    authToken {\n      accessToken\n      refreshToken\n      tokenType\n      expiresIn\n    }\n    errors {\n      message\n      code\n      field\n    }\n  }\n}": types.CreateSessionMutationDocument,
    "query MyShiftAssignmentsQuery($startDate: ISO8601Date!, $endDate: ISO8601Date!) {\n  myShiftAssignments(startDate: $startDate, endDate: $endDate) {\n    id\n    city\n    startTime\n    endTime\n    status\n    driver {\n      id\n    }\n    vehicle {\n      id\n      displayName\n    }\n    createdAt\n    updatedAt\n  }\n}": types.MyShiftAssignmentsQueryDocument,
    "query RevenueRecordsQuery($startDate: ISO8601Date, $endDate: ISO8601Date) {\n  revenueRecords(startDate: $startDate, endDate: $endDate) {\n    id\n    globalId\n    totalRevenue\n    totalProfit\n    reconciled\n    source\n    createdAt\n    updatedAt\n    driver {\n      id\n      fullName\n    }\n    shiftAssignment {\n      id\n      startTime\n      endTime\n      city\n      vehicle {\n        id\n        displayName\n      }\n    }\n  }\n}": types.RevenueRecordsQueryDocument,
    "mutation PauseShiftMutation {\n  pauseShift {\n    shiftEvent {\n      id\n      eventType\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": types.PauseShiftMutationDocument,
    "mutation ResumeShiftMutation {\n  resumeShift {\n    shiftEvent {\n      id\n      eventType\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": types.ResumeShiftMutationDocument,
    "query TodayShiftsQuery {\n  todayShifts {\n    id\n    globalId\n    city\n    startTime\n    actualStartTime\n    endTime\n    actualEndTime\n    status\n    driver {\n      id\n      globalId\n      fullName\n      email\n      phoneNumber\n      createdAt\n    }\n    vehicle {\n      id\n      globalId\n      licensePlate\n      model\n      make\n      yearOfManufacture\n      latestOdometer\n      displayName\n      latestRange\n      telematicsSource\n    }\n    shiftEvents {\n      id\n      globalId\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      createdAt\n    }\n    revenueRecords {\n      id\n      globalId\n      totalRevenue\n      totalProfit\n      reconciled\n      createdAt\n    }\n    createdAt\n    updatedAt\n  }\n}": types.TodayShiftsQueryDocument,
    "query TodaysShiftEventsQuery {\n  todaysShiftEvents {\n    id\n    globalId\n    eventType\n    odometer\n    vehicleRange\n    gpsLat\n    gpsLon\n    notes\n    createdAt\n    shiftAssignment {\n      id\n      globalId\n      vehicle {\n        id\n        displayName\n        licensePlate\n      }\n    }\n  }\n}": types.TodaysShiftEventsQueryDocument,
    "mutation UpdateVehicleMutation($input: UpdateVehicleInput!, $vehicleId: ID!) {\n  updateVehicle(input: $input, vehicleId: $vehicleId) {\n    vehicle {\n      ...VehicleFragment\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": types.UpdateVehicleMutationDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation ClockInMutation($input: ClockInInput!, $vehicleId: ID!) {\n  clockIn(input: $input, vehicleId: $vehicleId) {\n    shiftEvent {\n      id\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"): (typeof documents)["mutation ClockInMutation($input: ClockInInput!, $vehicleId: ID!) {\n  clockIn(input: $input, vehicleId: $vehicleId) {\n    shiftEvent {\n      id\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query VehiclesQuery {\n  vehicles {\n    ...VehicleFragment\n  }\n}\n\nfragment VehicleFragment on Vehicle {\n  id\n  globalId\n  make\n  model\n  licensePlate\n  yearOfManufacture\n  displayName\n  latestOdometer\n  latestRange\n  telematicsSource\n  vehicleImageUrl\n  createdAt\n  updatedAt\n  inUse\n}"): (typeof documents)["query VehiclesQuery {\n  vehicles {\n    ...VehicleFragment\n  }\n}\n\nfragment VehicleFragment on Vehicle {\n  id\n  globalId\n  make\n  model\n  licensePlate\n  yearOfManufacture\n  displayName\n  latestOdometer\n  latestRange\n  telematicsSource\n  vehicleImageUrl\n  createdAt\n  updatedAt\n  inUse\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation ClockOutMutation($input: ClockOutInput!) {\n  clockOut(input: $input) {\n    shiftEvent {\n      id\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"): (typeof documents)["mutation ClockOutMutation($input: ClockOutInput!) {\n  clockOut(input: $input) {\n    shiftEvent {\n      id\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CurrentShiftQuery {\n  currentShift {\n    ...CurrentShiftFragment\n  }\n}\n\nfragment CurrentShiftFragment on ShiftAssignment {\n  id\n  status\n  city\n  startTime\n  endTime\n  driver {\n    id\n    fullName\n    email\n  }\n  vehicle {\n    id\n    licensePlate\n    model\n    yearOfManufacture\n    latestOdometer\n    latestRange\n  }\n  shiftEvents {\n    id\n    eventType\n    odometer\n    vehicleRange\n    gpsLat\n    gpsLon\n    notes\n    createdAt\n  }\n}"): (typeof documents)["query CurrentShiftQuery {\n  currentShift {\n    ...CurrentShiftFragment\n  }\n}\n\nfragment CurrentShiftFragment on ShiftAssignment {\n  id\n  status\n  city\n  startTime\n  endTime\n  driver {\n    id\n    fullName\n    email\n  }\n  vehicle {\n    id\n    licensePlate\n    model\n    yearOfManufacture\n    latestOdometer\n    latestRange\n  }\n  shiftEvents {\n    id\n    eventType\n    odometer\n    vehicleRange\n    gpsLat\n    gpsLon\n    notes\n    createdAt\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateExpenseMutation($input: CreateExpenseInput!) {\n  createExpense(input: $input) {\n    expense {\n      id\n      globalId\n      amount\n      category\n      date\n      receiptKey\n      createdAt\n      updatedAt\n      user {\n        id\n        firstName\n        lastName\n        email\n      }\n      vehicle {\n        id\n        displayName\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"): (typeof documents)["mutation CreateExpenseMutation($input: CreateExpenseInput!) {\n  createExpense(input: $input) {\n    expense {\n      id\n      globalId\n      amount\n      category\n      date\n      receiptKey\n      createdAt\n      updatedAt\n      user {\n        id\n        firstName\n        lastName\n        email\n      }\n      vehicle {\n        id\n        displayName\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ExpenseStatsQuery($startDate: ISO8601Date, $endDate: ISO8601Date) {\n  expenseStats(startDate: $startDate, endDate: $endDate) {\n    totalAmount\n    count\n    categoryTotals\n  }\n}"): (typeof documents)["query ExpenseStatsQuery($startDate: ISO8601Date, $endDate: ISO8601Date) {\n  expenseStats(startDate: $startDate, endDate: $endDate) {\n    totalAmount\n    count\n    categoryTotals\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ExpensesQuery($startDate: ISO8601Date, $endDate: ISO8601Date, $pagination: PaginationInput!) {\n  expenses(startDate: $startDate, endDate: $endDate, pagination: $pagination) {\n    items {\n      id\n      globalId\n      amount\n      category\n      date\n      receiptKey\n      createdAt\n      updatedAt\n      user {\n        id\n        firstName\n        lastName\n        email\n      }\n      vehicle {\n        id\n        displayName\n      }\n    }\n    pagination {\n      currentPage\n      firstPage\n      lastPage\n      nextPage\n      pageCount\n      pageSize\n      prevPage\n      totalSize\n    }\n  }\n}"): (typeof documents)["query ExpensesQuery($startDate: ISO8601Date, $endDate: ISO8601Date, $pagination: PaginationInput!) {\n  expenses(startDate: $startDate, endDate: $endDate, pagination: $pagination) {\n    items {\n      id\n      globalId\n      amount\n      category\n      date\n      receiptKey\n      createdAt\n      updatedAt\n      user {\n        id\n        firstName\n        lastName\n        email\n      }\n      vehicle {\n        id\n        displayName\n      }\n    }\n    pagination {\n      currentPage\n      firstPage\n      lastPage\n      nextPage\n      pageCount\n      pageSize\n      prevPage\n      totalSize\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateSessionMutation($input: CreateSessionInput!) {\n  createSession(input: $input) {\n    user {\n      id\n      email\n      firstName\n      lastName\n      fullName\n      driver {\n        id\n        fullName\n      }\n    }\n    authToken {\n      accessToken\n      refreshToken\n      tokenType\n      expiresIn\n    }\n    errors {\n      message\n      code\n      field\n    }\n  }\n}"): (typeof documents)["mutation CreateSessionMutation($input: CreateSessionInput!) {\n  createSession(input: $input) {\n    user {\n      id\n      email\n      firstName\n      lastName\n      fullName\n      driver {\n        id\n        fullName\n      }\n    }\n    authToken {\n      accessToken\n      refreshToken\n      tokenType\n      expiresIn\n    }\n    errors {\n      message\n      code\n      field\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query MyShiftAssignmentsQuery($startDate: ISO8601Date!, $endDate: ISO8601Date!) {\n  myShiftAssignments(startDate: $startDate, endDate: $endDate) {\n    id\n    city\n    startTime\n    endTime\n    status\n    driver {\n      id\n    }\n    vehicle {\n      id\n      displayName\n    }\n    createdAt\n    updatedAt\n  }\n}"): (typeof documents)["query MyShiftAssignmentsQuery($startDate: ISO8601Date!, $endDate: ISO8601Date!) {\n  myShiftAssignments(startDate: $startDate, endDate: $endDate) {\n    id\n    city\n    startTime\n    endTime\n    status\n    driver {\n      id\n    }\n    vehicle {\n      id\n      displayName\n    }\n    createdAt\n    updatedAt\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query RevenueRecordsQuery($startDate: ISO8601Date, $endDate: ISO8601Date) {\n  revenueRecords(startDate: $startDate, endDate: $endDate) {\n    id\n    globalId\n    totalRevenue\n    totalProfit\n    reconciled\n    source\n    createdAt\n    updatedAt\n    driver {\n      id\n      fullName\n    }\n    shiftAssignment {\n      id\n      startTime\n      endTime\n      city\n      vehicle {\n        id\n        displayName\n      }\n    }\n  }\n}"): (typeof documents)["query RevenueRecordsQuery($startDate: ISO8601Date, $endDate: ISO8601Date) {\n  revenueRecords(startDate: $startDate, endDate: $endDate) {\n    id\n    globalId\n    totalRevenue\n    totalProfit\n    reconciled\n    source\n    createdAt\n    updatedAt\n    driver {\n      id\n      fullName\n    }\n    shiftAssignment {\n      id\n      startTime\n      endTime\n      city\n      vehicle {\n        id\n        displayName\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation PauseShiftMutation {\n  pauseShift {\n    shiftEvent {\n      id\n      eventType\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"): (typeof documents)["mutation PauseShiftMutation {\n  pauseShift {\n    shiftEvent {\n      id\n      eventType\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation ResumeShiftMutation {\n  resumeShift {\n    shiftEvent {\n      id\n      eventType\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"): (typeof documents)["mutation ResumeShiftMutation {\n  resumeShift {\n    shiftEvent {\n      id\n      eventType\n      shiftAssignment {\n        id\n        status\n        driver {\n          id\n          fullName\n        }\n        vehicle {\n          id\n          licensePlate\n          model\n        }\n      }\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query TodayShiftsQuery {\n  todayShifts {\n    id\n    globalId\n    city\n    startTime\n    actualStartTime\n    endTime\n    actualEndTime\n    status\n    driver {\n      id\n      globalId\n      fullName\n      email\n      phoneNumber\n      createdAt\n    }\n    vehicle {\n      id\n      globalId\n      licensePlate\n      model\n      make\n      yearOfManufacture\n      latestOdometer\n      displayName\n      latestRange\n      telematicsSource\n    }\n    shiftEvents {\n      id\n      globalId\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      createdAt\n    }\n    revenueRecords {\n      id\n      globalId\n      totalRevenue\n      totalProfit\n      reconciled\n      createdAt\n    }\n    createdAt\n    updatedAt\n  }\n}"): (typeof documents)["query TodayShiftsQuery {\n  todayShifts {\n    id\n    globalId\n    city\n    startTime\n    actualStartTime\n    endTime\n    actualEndTime\n    status\n    driver {\n      id\n      globalId\n      fullName\n      email\n      phoneNumber\n      createdAt\n    }\n    vehicle {\n      id\n      globalId\n      licensePlate\n      model\n      make\n      yearOfManufacture\n      latestOdometer\n      displayName\n      latestRange\n      telematicsSource\n    }\n    shiftEvents {\n      id\n      globalId\n      eventType\n      odometer\n      vehicleRange\n      gpsLat\n      gpsLon\n      notes\n      createdAt\n    }\n    revenueRecords {\n      id\n      globalId\n      totalRevenue\n      totalProfit\n      reconciled\n      createdAt\n    }\n    createdAt\n    updatedAt\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query TodaysShiftEventsQuery {\n  todaysShiftEvents {\n    id\n    globalId\n    eventType\n    odometer\n    vehicleRange\n    gpsLat\n    gpsLon\n    notes\n    createdAt\n    shiftAssignment {\n      id\n      globalId\n      vehicle {\n        id\n        displayName\n        licensePlate\n      }\n    }\n  }\n}"): (typeof documents)["query TodaysShiftEventsQuery {\n  todaysShiftEvents {\n    id\n    globalId\n    eventType\n    odometer\n    vehicleRange\n    gpsLat\n    gpsLon\n    notes\n    createdAt\n    shiftAssignment {\n      id\n      globalId\n      vehicle {\n        id\n        displayName\n        licensePlate\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdateVehicleMutation($input: UpdateVehicleInput!, $vehicleId: ID!) {\n  updateVehicle(input: $input, vehicleId: $vehicleId) {\n    vehicle {\n      ...VehicleFragment\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"): (typeof documents)["mutation UpdateVehicleMutation($input: UpdateVehicleInput!, $vehicleId: ID!) {\n  updateVehicle(input: $input, vehicleId: $vehicleId) {\n    vehicle {\n      ...VehicleFragment\n    }\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;