/* eslint-disable */
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Maybe<T> = T | null;
export type InputMaybe<T> = T | null | undefined;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** An ISO 8601-encoded date */
  ISO8601Date: { input: any; output: any; }
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: any; output: any; }
  /** Represents untyped JSON */
  JSON: { input: any; output: any; }
};

/** Authentication tokens */
export type AuthToken = {
  __typename?: 'AuthToken';
  accessToken: Scalars['String']['output'];
  expiresIn: Scalars['Int']['output'];
  refreshToken: Scalars['String']['output'];
  tokenType: Scalars['String']['output'];
};

/** The possible cities for shift assignments */
export const CityEnum = {
  /** Accra */
  Accra: 'accra',
  /** Kumasi */
  Kumasi: 'kumasi',
  /** Takoradi */
  Takoradi: 'takoradi'
} as const;

export type CityEnum = typeof CityEnum[keyof typeof CityEnum];
/** Input type for clocking in to a shift */
export type ClockInInput = {
  /** GPS latitude */
  gpsLat?: InputMaybe<Scalars['Float']['input']>;
  /** GPS longitude */
  gpsLon?: InputMaybe<Scalars['Float']['input']>;
  /** Additional notes for the clock in event */
  notes?: InputMaybe<Scalars['String']['input']>;
  /** Current odometer reading */
  odometer?: InputMaybe<Scalars['Int']['input']>;
  /** ID of the shift assignment to clock into (optional - will auto-find active shift if not provided) */
  shiftAssignmentId?: InputMaybe<Scalars['Int']['input']>;
  /** Current vehicle range */
  vehicleRange?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of ClockIn. */
export type ClockInPayload = {
  __typename?: 'ClockInPayload';
  /** An array of error messages */
  errors: Array<Error>;
  shiftEvent?: Maybe<ShiftEvent>;
};

/** Input type for clocking out of a shift */
export type ClockOutInput = {
  /** Bolt earnings for the shift */
  boltEarnings?: InputMaybe<Scalars['Float']['input']>;
  /** GPS latitude */
  gpsLat?: InputMaybe<Scalars['Float']['input']>;
  /** GPS longitude */
  gpsLon?: InputMaybe<Scalars['Float']['input']>;
  /** Additional notes for the clock out event */
  notes?: InputMaybe<Scalars['String']['input']>;
  /** Current odometer reading */
  odometer?: InputMaybe<Scalars['Int']['input']>;
  /** Uber earnings for the shift */
  uberEarnings?: InputMaybe<Scalars['Float']['input']>;
  /** Current vehicle range */
  vehicleRange?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of ClockOut. */
export type ClockOutPayload = {
  __typename?: 'ClockOutPayload';
  /** An array of error messages */
  errors: Array<Error>;
  shiftEvent?: Maybe<ShiftEvent>;
};

/** Input type for creating an expense */
export type CreateExpenseInput = {
  /** Expense amount */
  amount: Scalars['Float']['input'];
  /** Expense category */
  category: Scalars['String']['input'];
  /** Expense date */
  date: Scalars['ISO8601Date']['input'];
  /** Description of the expense (required when category is 'other') */
  description?: InputMaybe<Scalars['String']['input']>;
  /** Receipt key for uploaded receipt (optional) */
  receiptKey?: InputMaybe<Scalars['String']['input']>;
  /** ID of the vehicle (optional) */
  vehicleId?: InputMaybe<Scalars['ID']['input']>;
};

/** Autogenerated return type of CreateExpense. */
export type CreateExpensePayload = {
  __typename?: 'CreateExpensePayload';
  /** An array of error messages */
  errors: Array<Error>;
  expense?: Maybe<Expense>;
};

/** Input type for creating a revenue record */
export type CreateRevenueRecordInput = {
  /** Date of the revenue record */
  date: Scalars['ISO8601Date']['input'];
  /** ID of the driver */
  driverId: Scalars['ID']['input'];
  /** Whether the revenue is reconciled (default: false) */
  reconciled?: InputMaybe<Scalars['Boolean']['input']>;
  /** Revenue source (bolt, uber, or off_trip) */
  source: RevenueSourceEnum;
  /** Total revenue amount */
  totalRevenue: Scalars['Float']['input'];
  /** ID of the vehicle */
  vehicleId: Scalars['ID']['input'];
};

/** Autogenerated return type of CreateRevenueRecord. */
export type CreateRevenueRecordPayload = {
  __typename?: 'CreateRevenueRecordPayload';
  /** An array of error messages */
  errors: Array<Error>;
  revenueRecord?: Maybe<RevenueRecord>;
};

/** Input type for creating a new session */
export type CreateSessionInput = {
  /** User's email address */
  email: Scalars['String']['input'];
  /** Login scope - either 'user' or 'staff' */
  loginScope: LoginScopeEnum;
  /** User's password */
  password: Scalars['String']['input'];
};

/** Autogenerated return type of CreateSession. */
export type CreateSessionPayload = {
  __typename?: 'CreateSessionPayload';
  authToken?: Maybe<AuthToken>;
  /** An array of error messages */
  errors: Array<Error>;
  user?: Maybe<User>;
};

/** Daily payroll breakdown for a driver */
export type DailyPayrollBreakdown = {
  __typename?: 'DailyPayrollBreakdown';
  amountDue: Scalars['Float']['output'];
  date: Scalars['ISO8601Date']['output'];
  revenue: Scalars['Float']['output'];
};

/** A driver in the system */
export type Driver = {
  __typename?: 'Driver';
  createdAt: Scalars['ISO8601DateTime']['output'];
  dob: Scalars['ISO8601Date']['output'];
  email: Scalars['String']['output'];
  fullName: Scalars['String']['output'];
  globalId: Scalars['String']['output'];
  id: Scalars['String']['output'];
  phoneNumber: Scalars['String']['output'];
  revenueRecords?: Maybe<Array<RevenueRecord>>;
  shiftAssignments?: Maybe<Array<ShiftAssignment>>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  user?: Maybe<User>;
  verified: Scalars['Boolean']['output'];
};

/** A group of revenue records for a specific driver and date */
export type DriverDateRevenueGroup = {
  __typename?: 'DriverDateRevenueGroup';
  /** Whether all revenue records in this group are reconciled */
  allReconciled: Scalars['Boolean']['output'];
  /** Date of the revenue records */
  date: Scalars['ISO8601Date']['output'];
  /** Driver ID */
  driverId: Scalars['String']['output'];
  /** Driver full name */
  driverName: Scalars['String']['output'];
  /** Number of revenue records in this group */
  revenueCount: Scalars['Int']['output'];
  /** List of revenue records in this group */
  revenueRecords: Array<RevenueRecord>;
  /** Revenue breakdown by source */
  sourceBreakdown: Scalars['JSON']['output'];
  /** Total profit of all revenue records in this group */
  totalProfit: Scalars['Float']['output'];
  /** Total revenue of all revenue records in this group */
  totalRevenue: Scalars['Float']['output'];
  /** Vehicle display name (if available) */
  vehicleName?: Maybe<Scalars['String']['output']>;
};

/** Payroll information for a driver */
export type DriverPayroll = {
  __typename?: 'DriverPayroll';
  amountDue: Scalars['Float']['output'];
  dailyBreakdown: Array<DailyPayrollBreakdown>;
  driver: Driver;
  startDate: Scalars['ISO8601Date']['output'];
};

/** Represents an error in the system */
export type Error = {
  __typename?: 'Error';
  code?: Maybe<Scalars['String']['output']>;
  field?: Maybe<Scalars['String']['output']>;
  message: Scalars['String']['output'];
};

/** An expense record */
export type Expense = {
  __typename?: 'Expense';
  /** Expense amount in dollars */
  amount: Scalars['Float']['output'];
  category: Scalars['String']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  date: Scalars['ISO8601Date']['output'];
  /** Description of the expense (used when category is 'other') */
  description?: Maybe<Scalars['String']['output']>;
  globalId: Scalars['String']['output'];
  id: Scalars['String']['output'];
  receiptKey?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  user?: Maybe<User>;
  vehicle?: Maybe<Vehicle>;
};

/** Finance details breakdown for a date range */
export type FinanceDetails = {
  __typename?: 'FinanceDetails';
  /** Net company earnings (revenue - payroll - expenses) */
  earnings: Scalars['Float']['output'];
  /** Total expenses for the period */
  totalExpenses: Scalars['Float']['output'];
  /** Total payroll due to drivers for the period */
  totalPayrollDue: Scalars['Float']['output'];
  /** Total revenue for the period */
  totalRevenue: Scalars['Float']['output'];
};

/** Paginated result for grouped expenses with statistics */
export type GroupedExpensesResult = {
  __typename?: 'GroupedExpensesResult';
  /** Total expenses grouped by category */
  categoryTotals: Scalars['JSON']['output'];
  errors: Array<Error>;
  items: Array<VehicleDateExpenseGroup>;
  pagination: Pagination;
  /** Total amount of all expenses */
  totalAmount: Scalars['Float']['output'];
};

/** Paginated result for grouped revenue records with statistics */
export type GroupedRevenueRecordsResult = {
  __typename?: 'GroupedRevenueRecordsResult';
  errors: Array<Error>;
  items: Array<DriverDateRevenueGroup>;
  pagination: Pagination;
  /** Total revenue and profit grouped by source */
  sourceTotals: Scalars['JSON']['output'];
  /** Total profit of all revenue records */
  totalProfit: Scalars['Float']['output'];
  /** Total revenue of all revenue records */
  totalRevenue: Scalars['Float']['output'];
};

/** The possible login scopes for authentication */
export const LoginScopeEnum = {
  /** Staff login scope */
  Staff: 'staff',
  /** Regular user login scope */
  User: 'user'
} as const;

export type LoginScopeEnum = typeof LoginScopeEnum[keyof typeof LoginScopeEnum];
export type Mutation = {
  __typename?: 'Mutation';
  /** Clock in to a shift assignment */
  clockIn?: Maybe<ClockInPayload>;
  /** Clock out of a shift assignment */
  clockOut?: Maybe<ClockOutPayload>;
  /** Create a new expense record */
  createExpense?: Maybe<CreateExpensePayload>;
  /** Create a new revenue record */
  createRevenueRecord?: Maybe<CreateRevenueRecordPayload>;
  /** Login a user/create a session */
  createSession?: Maybe<CreateSessionPayload>;
  /** Pause an active shift assignment */
  pauseShift?: Maybe<PauseShiftPayload>;
  /** Resume a paused shift assignment */
  resumeShift?: Maybe<ResumeShiftPayload>;
  /** Update revenue record reconciled status */
  updateRevenueRecord?: Maybe<UpdateRevenueRecordPayload>;
  /** Update vehicle details */
  updateVehicle?: Maybe<UpdateVehiclePayload>;
};


export type MutationClockInArgs = {
  input: ClockInInput;
  vehicleId: Scalars['ID']['input'];
};


export type MutationClockOutArgs = {
  input: ClockOutInput;
};


export type MutationCreateExpenseArgs = {
  input: CreateExpenseInput;
};


export type MutationCreateRevenueRecordArgs = {
  input: CreateRevenueRecordInput;
};


export type MutationCreateSessionArgs = {
  input: CreateSessionInput;
};


export type MutationUpdateRevenueRecordArgs = {
  reconciled: Scalars['Boolean']['input'];
  revenueRecordId: Scalars['ID']['input'];
};


export type MutationUpdateVehicleArgs = {
  input: UpdateVehicleInput;
  vehicleId: Scalars['ID']['input'];
};

/** Represents a paginated list of results */
export type PaginatedResultExpense = {
  __typename?: 'PaginatedResultExpense';
  errors: Array<Error>;
  items: Array<Expense>;
  pagination: Pagination;
};

/** Represents pagination metadata for a result set */
export type Pagination = {
  __typename?: 'Pagination';
  /** Current page */
  currentPage: Scalars['Int']['output'];
  /** Is this the first page? */
  firstPage: Scalars['Boolean']['output'];
  /** Is this the last page? */
  lastPage: Scalars['Boolean']['output'];
  /** Next page */
  nextPage?: Maybe<Scalars['Int']['output']>;
  /** Number of pages available */
  pageCount?: Maybe<Scalars['Int']['output']>;
  /** Number of items per page */
  pageSize: Scalars['Int']['output'];
  /** Previous page */
  prevPage?: Maybe<Scalars['Int']['output']>;
  /** Total size of items that match this query */
  totalSize: Scalars['Int']['output'];
};

/** Input type for pagination parameters */
export type PaginationInput = {
  /** The page number to fetch (starts at 1) */
  page?: InputMaybe<Scalars['Int']['input']>;
  /** Number of items per page */
  perPage?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of PauseShift. */
export type PauseShiftPayload = {
  __typename?: 'PauseShiftPayload';
  /** An array of error messages */
  errors: Array<Error>;
  shiftEvent?: Maybe<ShiftEvent>;
};

/** Payroll information for all drivers */
export type Payroll = {
  __typename?: 'Payroll';
  driverPayrolls: Array<DriverPayroll>;
  totalAmountDue: Scalars['Float']['output'];
};

/** A permission in the system */
export type Permission = {
  __typename?: 'Permission';
  createdAt: Scalars['ISO8601DateTime']['output'];
  globalId: Scalars['String']['output'];
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  slug: PermissionEnum;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** The possible permissions in the system */
export const PermissionEnum = {
  /** View Drivers */
  DriverReadAccess: 'driver_read_access',
  /** Manage Drivers */
  DriverWriteAccess: 'driver_write_access',
  /** View Expenses */
  ExpenseReadAccess: 'expense_read_access',
  /** Manage Expenses */
  ExpenseWriteAccess: 'expense_write_access',
  /** View Payroll */
  PayrollReadAccess: 'payroll_read_access',
  /** Manage Payroll */
  PayrollWriteAccess: 'payroll_write_access',
  /** View Revenue */
  RevenueReadAccess: 'revenue_read_access',
  /** Manage Revenue */
  RevenueWriteAccess: 'revenue_write_access',
  /** View Shifts */
  ShiftReadAccess: 'shift_read_access',
  /** Manage Shifts */
  ShiftWriteAccess: 'shift_write_access',
  /** View Users */
  UserReadAccess: 'user_read_access',
  /** Manage Users */
  UserWriteAccess: 'user_write_access',
  /** View Vehicles */
  VehicleReadAccess: 'vehicle_read_access',
  /** Manage Vehicles */
  VehicleWriteAccess: 'vehicle_write_access'
} as const;

export type PermissionEnum = typeof PermissionEnum[keyof typeof PermissionEnum];
export type Query = {
  __typename?: 'Query';
  /** Get the current shift */
  currentShift?: Maybe<ShiftAssignment>;
  /** Get the current authenticated user */
  currentUser?: Maybe<User>;
  /** Get all drivers in the system */
  drivers: Array<Driver>;
  /** Get all expenses within a date range */
  expenses?: Maybe<PaginatedResultExpense>;
  /** Get finance details breakdown for a date range */
  financeDetails: FinanceDetails;
  /** Get expenses grouped by vehicle and date within a date range */
  groupedExpenses: GroupedExpensesResult;
  /** Get revenue records grouped by driver and date within a date range */
  groupedRevenueRecords: GroupedRevenueRecordsResult;
  /** Get payroll information for the authenticated driver within a date range */
  myPayroll?: Maybe<DriverPayroll>;
  /** Get shift assignments for the current driver within a date range */
  myShiftAssignments: Array<ShiftAssignment>;
  /** Get all drivers with their shift assignments for payroll calculation */
  payroll: Payroll;
  /** Get all revenue records within a date range */
  revenueRecords: Array<RevenueRecord>;
  /** Get today's shifts */
  todayShifts: Array<ShiftAssignment>;
  /** Get today's shift events for the current driver */
  todaysShiftEvents: Array<ShiftEvent>;
  /** Get all vehicles in the system */
  vehicles: Array<Vehicle>;
};


export type QueryExpensesArgs = {
  endDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
  pagination: PaginationInput;
  startDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
};


export type QueryFinanceDetailsArgs = {
  endDate: Scalars['ISO8601Date']['input'];
  startDate: Scalars['ISO8601Date']['input'];
};


export type QueryGroupedExpensesArgs = {
  driverId?: InputMaybe<Scalars['String']['input']>;
  endDate: Scalars['ISO8601Date']['input'];
  pagination: PaginationInput;
  startDate: Scalars['ISO8601Date']['input'];
};


export type QueryGroupedRevenueRecordsArgs = {
  driverId?: InputMaybe<Scalars['String']['input']>;
  endDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
  pagination: PaginationInput;
  startDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
};


export type QueryMyPayrollArgs = {
  endDate: Scalars['ISO8601Date']['input'];
  startDate: Scalars['ISO8601Date']['input'];
};


export type QueryMyShiftAssignmentsArgs = {
  endDate: Scalars['ISO8601Date']['input'];
  startDate: Scalars['ISO8601Date']['input'];
};


export type QueryPayrollArgs = {
  endDate: Scalars['ISO8601Date']['input'];
  startDate: Scalars['ISO8601Date']['input'];
};


export type QueryRevenueRecordsArgs = {
  endDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
  startDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
};

/** Autogenerated return type of ResumeShift. */
export type ResumeShiftPayload = {
  __typename?: 'ResumeShiftPayload';
  /** An array of error messages */
  errors: Array<Error>;
  shiftEvent?: Maybe<ShiftEvent>;
};

/** A revenue record for a shift */
export type RevenueRecord = {
  __typename?: 'RevenueRecord';
  createdAt: Scalars['ISO8601DateTime']['output'];
  driver: Driver;
  globalId: Scalars['String']['output'];
  id: Scalars['String']['output'];
  reconciled: Scalars['Boolean']['output'];
  shiftAssignment: ShiftAssignment;
  source: RevenueSourceEnum;
  totalProfit: Scalars['Float']['output'];
  totalRevenue: Scalars['Float']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** The possible sources for revenue records */
export const RevenueSourceEnum = {
  /** Bolt */
  Bolt: 'bolt',
  /** Off trip */
  OffTrip: 'off_trip',
  /** Uber */
  Uber: 'uber'
} as const;

export type RevenueSourceEnum = typeof RevenueSourceEnum[keyof typeof RevenueSourceEnum];
/** A shift assignment for a driver */
export type ShiftAssignment = {
  __typename?: 'ShiftAssignment';
  actualEndTime?: Maybe<Scalars['ISO8601DateTime']['output']>;
  actualStartTime?: Maybe<Scalars['ISO8601DateTime']['output']>;
  city: CityEnum;
  createdAt: Scalars['ISO8601DateTime']['output'];
  driver: Driver;
  endTime: Scalars['ISO8601DateTime']['output'];
  globalId: Scalars['String']['output'];
  id: Scalars['String']['output'];
  revenueRecords?: Maybe<Array<RevenueRecord>>;
  shiftEvents?: Maybe<Array<ShiftEvent>>;
  startTime: Scalars['ISO8601DateTime']['output'];
  status: ShiftStatusEnum;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  vehicle?: Maybe<Vehicle>;
};

/** An event that occurs during a shift */
export type ShiftEvent = {
  __typename?: 'ShiftEvent';
  createdAt: Scalars['ISO8601DateTime']['output'];
  eventType: ShiftEventTypeEnum;
  globalId: Scalars['String']['output'];
  gpsLat?: Maybe<Scalars['Float']['output']>;
  gpsLon?: Maybe<Scalars['Float']['output']>;
  id: Scalars['String']['output'];
  notes?: Maybe<Scalars['String']['output']>;
  odometer?: Maybe<Scalars['Int']['output']>;
  shiftAssignment: ShiftAssignment;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  vehicleRange?: Maybe<Scalars['Int']['output']>;
};

/** The possible types of shift events */
export const ShiftEventTypeEnum = {
  /** A clock in event */
  ClockIn: 'clock_in',
  /** A clock out event */
  ClockOut: 'clock_out',
  /** A pause event */
  Pause: 'pause',
  /** A resume event */
  Resume: 'resume',
  /** A telemetry snapshot event */
  TelemetrySnapshot: 'telemetry_snapshot'
} as const;

export type ShiftEventTypeEnum = typeof ShiftEventTypeEnum[keyof typeof ShiftEventTypeEnum];
/** The possible statuses for a shift assignment */
export const ShiftStatusEnum = {
  /** Shift is currently active */
  Active: 'active',
  /** Shift has been completed */
  Completed: 'completed',
  /** Shift was missed */
  Missed: 'missed',
  /** Shift is paused */
  Paused: 'paused',
  /** Shift is scheduled but not yet started */
  Scheduled: 'scheduled'
} as const;

export type ShiftStatusEnum = typeof ShiftStatusEnum[keyof typeof ShiftStatusEnum];
/** Autogenerated return type of UpdateRevenueRecord. */
export type UpdateRevenueRecordPayload = {
  __typename?: 'UpdateRevenueRecordPayload';
  /** An array of error messages */
  errors: Array<Error>;
  revenueRecord?: Maybe<RevenueRecord>;
};

/** Input type for updating a vehicle */
export type UpdateVehicleInput = {
  /** Latest odometer reading */
  latestOdometer?: InputMaybe<Scalars['Int']['input']>;
  /** Latest vehicle range */
  latestRange?: InputMaybe<Scalars['Int']['input']>;
  /** Vehicle license plate */
  licensePlate?: InputMaybe<Scalars['String']['input']>;
  /** Vehicle make */
  make?: InputMaybe<Scalars['String']['input']>;
  /** Vehicle model */
  model?: InputMaybe<Scalars['String']['input']>;
  /** Telematics source */
  telematicsSource?: InputMaybe<Scalars['Int']['input']>;
  /** Year of manufacture */
  yearOfManufacture?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of UpdateVehicle. */
export type UpdateVehiclePayload = {
  __typename?: 'UpdateVehiclePayload';
  /** An array of error messages */
  errors: Array<Error>;
  vehicle?: Maybe<Vehicle>;
};

/** A user in the system */
export type User = {
  __typename?: 'User';
  createdAt: Scalars['ISO8601DateTime']['output'];
  driver?: Maybe<Driver>;
  email: Scalars['String']['output'];
  expenses?: Maybe<Array<Expense>>;
  firstName: Scalars['String']['output'];
  fullName: Scalars['String']['output'];
  globalId: Scalars['String']['output'];
  id: Scalars['String']['output'];
  lastName: Scalars['String']['output'];
  lastSignInAt?: Maybe<Scalars['ISO8601DateTime']['output']>;
  permissions?: Maybe<Array<Permission>>;
  signInCount: Scalars['Int']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** A vehicle in the system */
export type Vehicle = {
  __typename?: 'Vehicle';
  createdAt: Scalars['ISO8601DateTime']['output'];
  displayName: Scalars['String']['output'];
  expenses?: Maybe<Array<Expense>>;
  globalId: Scalars['String']['output'];
  id: Scalars['String']['output'];
  inUse: Scalars['Boolean']['output'];
  latestOdometer: Scalars['Int']['output'];
  latestRange: Scalars['Int']['output'];
  licensePlate: Scalars['String']['output'];
  make: Scalars['String']['output'];
  model: Scalars['String']['output'];
  shiftAssignments?: Maybe<Array<ShiftAssignment>>;
  telematicsSource: Scalars['Int']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
  vehicleImageUrl?: Maybe<Scalars['String']['output']>;
  yearOfManufacture: Scalars['Int']['output'];
};

/** A group of expenses for a specific vehicle and date */
export type VehicleDateExpenseGroup = {
  __typename?: 'VehicleDateExpenseGroup';
  /** Date of the expenses */
  date: Scalars['ISO8601Date']['output'];
  /** Number of expenses in this group */
  expenseCount: Scalars['Int']['output'];
  /** List of expenses in this group */
  expenses: Array<Expense>;
  /** Total amount of all expenses in this group (in dollars) */
  totalAmount: Scalars['Float']['output'];
  /** Vehicle ID (or 'no-vehicle' if no vehicle) */
  vehicleId: Scalars['String']['output'];
  /** Vehicle display name (or 'No Vehicle' if no vehicle) */
  vehicleName: Scalars['String']['output'];
};

export type ClockInMutationMutationVariables = Exact<{
  input: ClockInInput;
  vehicleId: Scalars['ID']['input'];
}>;


export type ClockInMutationMutation = { __typename?: 'Mutation', clockIn?: { __typename?: 'ClockInPayload', shiftEvent?: { __typename?: 'ShiftEvent', id: string, eventType: ShiftEventTypeEnum, odometer?: number | null, vehicleRange?: number | null, gpsLat?: number | null, gpsLon?: number | null, notes?: string | null, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, status: ShiftStatusEnum, driver: { __typename?: 'Driver', id: string, fullName: string }, vehicle?: { __typename?: 'Vehicle', id: string, licensePlate: string, model: string } | null } } | null, errors: Array<{ __typename?: 'Error', message: string, field?: string | null, code?: string | null }> } | null };

export type VehiclesQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type VehiclesQueryQuery = { __typename?: 'Query', vehicles: Array<(
    { __typename?: 'Vehicle' }
    & { ' $fragmentRefs'?: { 'VehicleFragmentFragment': VehicleFragmentFragment } }
  )> };

export type VehicleFragmentFragment = { __typename?: 'Vehicle', id: string, globalId: string, make: string, model: string, licensePlate: string, yearOfManufacture: number, displayName: string, latestOdometer: number, latestRange: number, telematicsSource: number, vehicleImageUrl?: string | null, createdAt: any, updatedAt: any, inUse: boolean } & { ' $fragmentName'?: 'VehicleFragmentFragment' };

export type ClockOutMutationMutationVariables = Exact<{
  input: ClockOutInput;
}>;


export type ClockOutMutationMutation = { __typename?: 'Mutation', clockOut?: { __typename?: 'ClockOutPayload', shiftEvent?: { __typename?: 'ShiftEvent', id: string, eventType: ShiftEventTypeEnum, odometer?: number | null, vehicleRange?: number | null, gpsLat?: number | null, gpsLon?: number | null, notes?: string | null, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, status: ShiftStatusEnum, driver: { __typename?: 'Driver', id: string, fullName: string }, vehicle?: { __typename?: 'Vehicle', id: string, licensePlate: string, model: string } | null } } | null, errors: Array<{ __typename?: 'Error', message: string, field?: string | null, code?: string | null }> } | null };

export type FinanceDetailsQueryQueryVariables = Exact<{
  startDate: Scalars['ISO8601Date']['input'];
  endDate: Scalars['ISO8601Date']['input'];
}>;


export type FinanceDetailsQueryQuery = { __typename?: 'Query', financeDetails: { __typename?: 'FinanceDetails', totalRevenue: number, totalPayrollDue: number, totalExpenses: number, earnings: number } };

export type CurrentShiftQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type CurrentShiftQueryQuery = { __typename?: 'Query', currentShift?: (
    { __typename?: 'ShiftAssignment' }
    & { ' $fragmentRefs'?: { 'CurrentShiftFragmentFragment': CurrentShiftFragmentFragment } }
  ) | null };

export type CurrentShiftFragmentFragment = { __typename?: 'ShiftAssignment', id: string, status: ShiftStatusEnum, city: CityEnum, startTime: any, endTime: any, driver: { __typename?: 'Driver', id: string, fullName: string, email: string }, vehicle?: { __typename?: 'Vehicle', id: string, licensePlate: string, model: string, yearOfManufacture: number, latestOdometer: number, latestRange: number } | null, shiftEvents?: Array<{ __typename?: 'ShiftEvent', id: string, eventType: ShiftEventTypeEnum, odometer?: number | null, vehicleRange?: number | null, gpsLat?: number | null, gpsLon?: number | null, notes?: string | null, createdAt: any }> | null } & { ' $fragmentName'?: 'CurrentShiftFragmentFragment' };

export type CurrentUserQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type CurrentUserQueryQuery = { __typename?: 'Query', currentUser?: { __typename?: 'User', id: string, globalId: string, email: string, firstName: string, lastName: string, fullName: string, createdAt: any, updatedAt: any, signInCount: number, permissions?: Array<{ __typename?: 'Permission', id: string, slug: PermissionEnum }> | null, driver?: { __typename?: 'Driver', id: string, fullName: string } | null } | null };

export type DriversQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type DriversQueryQuery = { __typename?: 'Query', drivers: Array<{ __typename?: 'Driver', id: string, globalId: string, fullName: string, email: string, phoneNumber: string, verified: boolean }> };

export type CreateExpenseMutationMutationVariables = Exact<{
  input: CreateExpenseInput;
}>;


export type CreateExpenseMutationMutation = { __typename?: 'Mutation', createExpense?: { __typename?: 'CreateExpensePayload', expense?: { __typename?: 'Expense', id: string, globalId: string, amount: number, category: string, date: any, receiptKey?: string | null, description?: string | null, createdAt: any, updatedAt: any, user?: { __typename?: 'User', id: string, firstName: string, lastName: string, email: string } | null, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string } | null } | null, errors: Array<{ __typename?: 'Error', message: string, field?: string | null, code?: string | null }> } | null };

export type ExpensesQueryQueryVariables = Exact<{
  startDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
  endDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
  pagination: PaginationInput;
}>;


export type ExpensesQueryQuery = { __typename?: 'Query', expenses?: { __typename?: 'PaginatedResultExpense', items: Array<{ __typename?: 'Expense', id: string, globalId: string, amount: number, category: string, date: any, receiptKey?: string | null, description?: string | null, createdAt: any, updatedAt: any, user?: { __typename?: 'User', id: string, firstName: string, lastName: string, email: string } | null, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string } | null }>, pagination: { __typename?: 'Pagination', currentPage: number, firstPage: boolean, lastPage: boolean, nextPage?: number | null, pageCount?: number | null, pageSize: number, prevPage?: number | null, totalSize: number } } | null };

export type GroupedExpensesQueryQueryVariables = Exact<{
  startDate: Scalars['ISO8601Date']['input'];
  endDate: Scalars['ISO8601Date']['input'];
  pagination: PaginationInput;
  driverId?: InputMaybe<Scalars['String']['input']>;
}>;


export type GroupedExpensesQueryQuery = { __typename?: 'Query', groupedExpenses: { __typename?: 'GroupedExpensesResult', totalAmount: number, categoryTotals: any, items: Array<{ __typename?: 'VehicleDateExpenseGroup', vehicleId: string, vehicleName: string, date: any, totalAmount: number, expenseCount: number, expenses: Array<{ __typename?: 'Expense', id: string, globalId: string, amount: number, category: string, date: any, receiptKey?: string | null, description?: string | null, createdAt: any, updatedAt: any, user?: { __typename?: 'User', id: string, firstName: string, lastName: string, email: string } | null, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string } | null }> }>, pagination: { __typename?: 'Pagination', currentPage: number, firstPage: boolean, lastPage: boolean, nextPage?: number | null, pageCount?: number | null, pageSize: number, prevPage?: number | null, totalSize: number } } };

export type CreateSessionMutationMutationVariables = Exact<{
  input: CreateSessionInput;
}>;


export type CreateSessionMutationMutation = { __typename?: 'Mutation', createSession?: { __typename?: 'CreateSessionPayload', user?: { __typename?: 'User', id: string, email: string, firstName: string, lastName: string, fullName: string, driver?: { __typename?: 'Driver', id: string, fullName: string } | null, permissions?: Array<{ __typename?: 'Permission', slug: PermissionEnum }> | null } | null, authToken?: { __typename?: 'AuthToken', accessToken: string, refreshToken: string, tokenType: string, expiresIn: number } | null, errors: Array<{ __typename?: 'Error', message: string, code?: string | null, field?: string | null }> } | null };

export type MyShiftAssignmentsQueryQueryVariables = Exact<{
  startDate: Scalars['ISO8601Date']['input'];
  endDate: Scalars['ISO8601Date']['input'];
}>;


export type MyShiftAssignmentsQueryQuery = { __typename?: 'Query', myShiftAssignments: Array<{ __typename?: 'ShiftAssignment', id: string, city: CityEnum, startTime: any, endTime: any, status: ShiftStatusEnum, createdAt: any, updatedAt: any, driver: { __typename?: 'Driver', id: string }, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string } | null }> };

export type MyPayrollQueryQueryVariables = Exact<{
  startDate: Scalars['ISO8601Date']['input'];
  endDate: Scalars['ISO8601Date']['input'];
}>;


export type MyPayrollQueryQuery = { __typename?: 'Query', myPayroll?: { __typename?: 'DriverPayroll', amountDue: number, startDate: any, dailyBreakdown: Array<{ __typename?: 'DailyPayrollBreakdown', date: any, revenue: number, amountDue: number }>, driver: { __typename?: 'Driver', id: string, globalId: string, fullName: string, email: string, phoneNumber: string } } | null };

export type PayrollQueryQueryVariables = Exact<{
  startDate: Scalars['ISO8601Date']['input'];
  endDate: Scalars['ISO8601Date']['input'];
}>;


export type PayrollQueryQuery = { __typename?: 'Query', payroll: { __typename?: 'Payroll', totalAmountDue: number, driverPayrolls: Array<{ __typename?: 'DriverPayroll', amountDue: number, startDate: any, dailyBreakdown: Array<{ __typename?: 'DailyPayrollBreakdown', date: any, revenue: number, amountDue: number }>, driver: { __typename?: 'Driver', id: string, globalId: string, fullName: string, email: string, phoneNumber: string } }> } };

export type CreateRevenueRecordMutationMutationVariables = Exact<{
  input: CreateRevenueRecordInput;
}>;


export type CreateRevenueRecordMutationMutation = { __typename?: 'Mutation', createRevenueRecord?: { __typename?: 'CreateRevenueRecordPayload', revenueRecord?: { __typename?: 'RevenueRecord', id: string, globalId: string, totalRevenue: number, totalProfit: number, reconciled: boolean, source: RevenueSourceEnum, createdAt: any, updatedAt: any, driver: { __typename?: 'Driver', id: string, fullName: string }, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, startTime: any, endTime: any, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string } | null } } | null, errors: Array<{ __typename?: 'Error', message: string, field?: string | null, code?: string | null }> } | null };

export type GroupedRevenueRecordsQueryQueryVariables = Exact<{
  startDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
  endDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
  pagination: PaginationInput;
  driverId?: InputMaybe<Scalars['String']['input']>;
}>;


export type GroupedRevenueRecordsQueryQuery = { __typename?: 'Query', groupedRevenueRecords: { __typename?: 'GroupedRevenueRecordsResult', totalRevenue: number, totalProfit: number, sourceTotals: any, items: Array<{ __typename?: 'DriverDateRevenueGroup', driverId: string, driverName: string, date: any, totalRevenue: number, totalProfit: number, allReconciled: boolean, revenueCount: number, vehicleName?: string | null, sourceBreakdown: any, revenueRecords: Array<{ __typename?: 'RevenueRecord', id: string, globalId: string, totalRevenue: number, totalProfit: number, reconciled: boolean, source: RevenueSourceEnum, createdAt: any, updatedAt: any, driver: { __typename?: 'Driver', id: string, fullName: string }, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, startTime: any, endTime: any, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string } | null } }> }>, pagination: { __typename?: 'Pagination', currentPage: number, firstPage: boolean, lastPage: boolean, nextPage?: number | null, pageCount?: number | null, pageSize: number, prevPage?: number | null, totalSize: number } } };

export type RevenueRecordsQueryQueryVariables = Exact<{
  startDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
  endDate?: InputMaybe<Scalars['ISO8601Date']['input']>;
}>;


export type RevenueRecordsQueryQuery = { __typename?: 'Query', revenueRecords: Array<{ __typename?: 'RevenueRecord', id: string, globalId: string, totalRevenue: number, totalProfit: number, reconciled: boolean, source: RevenueSourceEnum, createdAt: any, updatedAt: any, driver: { __typename?: 'Driver', id: string, fullName: string }, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, startTime: any, endTime: any, city: CityEnum, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string } | null } }> };

export type UpdateRevenueRecordMutationMutationVariables = Exact<{
  revenueRecordId: Scalars['ID']['input'];
  reconciled: Scalars['Boolean']['input'];
}>;


export type UpdateRevenueRecordMutationMutation = { __typename?: 'Mutation', updateRevenueRecord?: { __typename?: 'UpdateRevenueRecordPayload', revenueRecord?: { __typename?: 'RevenueRecord', id: string, globalId: string, totalRevenue: number, totalProfit: number, reconciled: boolean, source: RevenueSourceEnum, createdAt: any, updatedAt: any, driver: { __typename?: 'Driver', id: string, fullName: string }, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, startTime: any, endTime: any, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string } | null } } | null, errors: Array<{ __typename?: 'Error', message: string, field?: string | null, code?: string | null }> } | null };

export type PauseShiftMutationMutationVariables = Exact<{ [key: string]: never; }>;


export type PauseShiftMutationMutation = { __typename?: 'Mutation', pauseShift?: { __typename?: 'PauseShiftPayload', shiftEvent?: { __typename?: 'ShiftEvent', id: string, eventType: ShiftEventTypeEnum, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, status: ShiftStatusEnum, driver: { __typename?: 'Driver', id: string, fullName: string }, vehicle?: { __typename?: 'Vehicle', id: string, licensePlate: string, model: string } | null } } | null, errors: Array<{ __typename?: 'Error', message: string, field?: string | null, code?: string | null }> } | null };

export type ResumeShiftMutationMutationVariables = Exact<{ [key: string]: never; }>;


export type ResumeShiftMutationMutation = { __typename?: 'Mutation', resumeShift?: { __typename?: 'ResumeShiftPayload', shiftEvent?: { __typename?: 'ShiftEvent', id: string, eventType: ShiftEventTypeEnum, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, status: ShiftStatusEnum, driver: { __typename?: 'Driver', id: string, fullName: string }, vehicle?: { __typename?: 'Vehicle', id: string, licensePlate: string, model: string } | null } } | null, errors: Array<{ __typename?: 'Error', message: string, field?: string | null, code?: string | null }> } | null };

export type TodayShiftsQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type TodayShiftsQueryQuery = { __typename?: 'Query', todayShifts: Array<{ __typename?: 'ShiftAssignment', id: string, globalId: string, city: CityEnum, startTime: any, actualStartTime?: any | null, endTime: any, actualEndTime?: any | null, status: ShiftStatusEnum, createdAt: any, updatedAt: any, driver: { __typename?: 'Driver', id: string, globalId: string, fullName: string, email: string, phoneNumber: string, createdAt: any }, vehicle?: { __typename?: 'Vehicle', id: string, globalId: string, licensePlate: string, model: string, make: string, yearOfManufacture: number, latestOdometer: number, displayName: string, latestRange: number, telematicsSource: number } | null, shiftEvents?: Array<{ __typename?: 'ShiftEvent', id: string, globalId: string, eventType: ShiftEventTypeEnum, odometer?: number | null, vehicleRange?: number | null, gpsLat?: number | null, gpsLon?: number | null, notes?: string | null, createdAt: any }> | null, revenueRecords?: Array<{ __typename?: 'RevenueRecord', id: string, globalId: string, totalRevenue: number, totalProfit: number, reconciled: boolean, createdAt: any }> | null }> };

export type TodaysShiftEventsQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type TodaysShiftEventsQueryQuery = { __typename?: 'Query', todaysShiftEvents: Array<{ __typename?: 'ShiftEvent', id: string, globalId: string, eventType: ShiftEventTypeEnum, odometer?: number | null, vehicleRange?: number | null, gpsLat?: number | null, gpsLon?: number | null, notes?: string | null, createdAt: any, shiftAssignment: { __typename?: 'ShiftAssignment', id: string, globalId: string, driver: { __typename?: 'Driver', id: string, fullName: string }, vehicle?: { __typename?: 'Vehicle', id: string, displayName: string, licensePlate: string } | null } }> };

export type UpdateVehicleMutationMutationVariables = Exact<{
  input: UpdateVehicleInput;
  vehicleId: Scalars['ID']['input'];
}>;


export type UpdateVehicleMutationMutation = { __typename?: 'Mutation', updateVehicle?: { __typename?: 'UpdateVehiclePayload', vehicle?: (
      { __typename?: 'Vehicle' }
      & { ' $fragmentRefs'?: { 'VehicleFragmentFragment': VehicleFragmentFragment } }
    ) | null, errors: Array<{ __typename?: 'Error', message: string, field?: string | null, code?: string | null }> } | null };

export const VehicleFragmentFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"VehicleFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Vehicle"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"make"}},{"kind":"Field","name":{"kind":"Name","value":"model"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"yearOfManufacture"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}},{"kind":"Field","name":{"kind":"Name","value":"latestOdometer"}},{"kind":"Field","name":{"kind":"Name","value":"latestRange"}},{"kind":"Field","name":{"kind":"Name","value":"telematicsSource"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleImageUrl"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"inUse"}}]}}]} as unknown as DocumentNode<VehicleFragmentFragment, unknown>;
export const CurrentShiftFragmentFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CurrentShiftFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ShiftAssignment"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"city"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"model"}},{"kind":"Field","name":{"kind":"Name","value":"yearOfManufacture"}},{"kind":"Field","name":{"kind":"Name","value":"latestOdometer"}},{"kind":"Field","name":{"kind":"Name","value":"latestRange"}}]}},{"kind":"Field","name":{"kind":"Name","value":"shiftEvents"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"eventType"}},{"kind":"Field","name":{"kind":"Name","value":"odometer"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleRange"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLat"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLon"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]}}]} as unknown as DocumentNode<CurrentShiftFragmentFragment, unknown>;
export const ClockInMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ClockInMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ClockInInput"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"vehicleId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"clockIn"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}},{"kind":"Argument","name":{"kind":"Name","value":"vehicleId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"vehicleId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"shiftEvent"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"eventType"}},{"kind":"Field","name":{"kind":"Name","value":"odometer"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleRange"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLat"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLon"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"model"}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"field"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]}}]}}]} as unknown as DocumentNode<ClockInMutationMutation, ClockInMutationMutationVariables>;
export const VehiclesQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"VehiclesQuery"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"vehicles"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"VehicleFragment"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"VehicleFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Vehicle"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"make"}},{"kind":"Field","name":{"kind":"Name","value":"model"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"yearOfManufacture"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}},{"kind":"Field","name":{"kind":"Name","value":"latestOdometer"}},{"kind":"Field","name":{"kind":"Name","value":"latestRange"}},{"kind":"Field","name":{"kind":"Name","value":"telematicsSource"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleImageUrl"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"inUse"}}]}}]} as unknown as DocumentNode<VehiclesQueryQuery, VehiclesQueryQueryVariables>;
export const ClockOutMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ClockOutMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ClockOutInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"clockOut"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"shiftEvent"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"eventType"}},{"kind":"Field","name":{"kind":"Name","value":"odometer"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleRange"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLat"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLon"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"model"}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"field"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]}}]}}]} as unknown as DocumentNode<ClockOutMutationMutation, ClockOutMutationMutationVariables>;
export const FinanceDetailsQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"FinanceDetailsQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"financeDetails"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"totalRevenue"}},{"kind":"Field","name":{"kind":"Name","value":"totalPayrollDue"}},{"kind":"Field","name":{"kind":"Name","value":"totalExpenses"}},{"kind":"Field","name":{"kind":"Name","value":"earnings"}}]}}]}}]} as unknown as DocumentNode<FinanceDetailsQueryQuery, FinanceDetailsQueryQueryVariables>;
export const CurrentShiftQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"CurrentShiftQuery"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentShift"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CurrentShiftFragment"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CurrentShiftFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ShiftAssignment"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"city"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"model"}},{"kind":"Field","name":{"kind":"Name","value":"yearOfManufacture"}},{"kind":"Field","name":{"kind":"Name","value":"latestOdometer"}},{"kind":"Field","name":{"kind":"Name","value":"latestRange"}}]}},{"kind":"Field","name":{"kind":"Name","value":"shiftEvents"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"eventType"}},{"kind":"Field","name":{"kind":"Name","value":"odometer"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleRange"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLat"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLon"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]}}]} as unknown as DocumentNode<CurrentShiftQueryQuery, CurrentShiftQueryQueryVariables>;
export const CurrentUserQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"CurrentUserQuery"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"signInCount"}},{"kind":"Field","name":{"kind":"Name","value":"permissions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"slug"}}]}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}}]}}]}}]} as unknown as DocumentNode<CurrentUserQueryQuery, CurrentUserQueryQueryVariables>;
export const DriversQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"DriversQuery"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"drivers"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"phoneNumber"}},{"kind":"Field","name":{"kind":"Name","value":"verified"}}]}}]}}]} as unknown as DocumentNode<DriversQueryQuery, DriversQueryQueryVariables>;
export const CreateExpenseMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateExpenseMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"CreateExpenseInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createExpense"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"expense"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"amount"}},{"kind":"Field","name":{"kind":"Name","value":"category"}},{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"receiptKey"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"field"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]}}]}}]} as unknown as DocumentNode<CreateExpenseMutationMutation, CreateExpenseMutationMutationVariables>;
export const ExpensesQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"ExpensesQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"pagination"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"PaginationInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"expenses"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"pagination"},"value":{"kind":"Variable","name":{"kind":"Name","value":"pagination"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"amount"}},{"kind":"Field","name":{"kind":"Name","value":"category"}},{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"receiptKey"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"pagination"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentPage"}},{"kind":"Field","name":{"kind":"Name","value":"firstPage"}},{"kind":"Field","name":{"kind":"Name","value":"lastPage"}},{"kind":"Field","name":{"kind":"Name","value":"nextPage"}},{"kind":"Field","name":{"kind":"Name","value":"pageCount"}},{"kind":"Field","name":{"kind":"Name","value":"pageSize"}},{"kind":"Field","name":{"kind":"Name","value":"prevPage"}},{"kind":"Field","name":{"kind":"Name","value":"totalSize"}}]}}]}}]}}]} as unknown as DocumentNode<ExpensesQueryQuery, ExpensesQueryQueryVariables>;
export const GroupedExpensesQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GroupedExpensesQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"pagination"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"PaginationInput"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"driverId"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"groupedExpenses"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"pagination"},"value":{"kind":"Variable","name":{"kind":"Name","value":"pagination"}}},{"kind":"Argument","name":{"kind":"Name","value":"driverId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"driverId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"vehicleId"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleName"}},{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"totalAmount"}},{"kind":"Field","name":{"kind":"Name","value":"expenseCount"}},{"kind":"Field","name":{"kind":"Name","value":"expenses"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"amount"}},{"kind":"Field","name":{"kind":"Name","value":"category"}},{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"receiptKey"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"pagination"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentPage"}},{"kind":"Field","name":{"kind":"Name","value":"firstPage"}},{"kind":"Field","name":{"kind":"Name","value":"lastPage"}},{"kind":"Field","name":{"kind":"Name","value":"nextPage"}},{"kind":"Field","name":{"kind":"Name","value":"pageCount"}},{"kind":"Field","name":{"kind":"Name","value":"pageSize"}},{"kind":"Field","name":{"kind":"Name","value":"prevPage"}},{"kind":"Field","name":{"kind":"Name","value":"totalSize"}}]}},{"kind":"Field","name":{"kind":"Name","value":"totalAmount"}},{"kind":"Field","name":{"kind":"Name","value":"categoryTotals"}}]}}]}}]} as unknown as DocumentNode<GroupedExpensesQueryQuery, GroupedExpensesQueryQueryVariables>;
export const CreateSessionMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateSessionMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"CreateSessionInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createSession"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"permissions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"slug"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"authToken"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"accessToken"}},{"kind":"Field","name":{"kind":"Name","value":"refreshToken"}},{"kind":"Field","name":{"kind":"Name","value":"tokenType"}},{"kind":"Field","name":{"kind":"Name","value":"expiresIn"}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"field"}}]}}]}}]}}]} as unknown as DocumentNode<CreateSessionMutationMutation, CreateSessionMutationMutationVariables>;
export const MyShiftAssignmentsQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"MyShiftAssignmentsQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"myShiftAssignments"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"city"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]}}]} as unknown as DocumentNode<MyShiftAssignmentsQueryQuery, MyShiftAssignmentsQueryQueryVariables>;
export const MyPayrollQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"MyPayrollQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"myPayroll"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"amountDue"}},{"kind":"Field","name":{"kind":"Name","value":"startDate"}},{"kind":"Field","name":{"kind":"Name","value":"dailyBreakdown"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"revenue"}},{"kind":"Field","name":{"kind":"Name","value":"amountDue"}}]}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"phoneNumber"}}]}}]}}]}}]} as unknown as DocumentNode<MyPayrollQueryQuery, MyPayrollQueryQueryVariables>;
export const PayrollQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PayrollQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"payroll"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"totalAmountDue"}},{"kind":"Field","name":{"kind":"Name","value":"driverPayrolls"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"amountDue"}},{"kind":"Field","name":{"kind":"Name","value":"startDate"}},{"kind":"Field","name":{"kind":"Name","value":"dailyBreakdown"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"revenue"}},{"kind":"Field","name":{"kind":"Name","value":"amountDue"}}]}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"phoneNumber"}}]}}]}}]}}]}}]} as unknown as DocumentNode<PayrollQueryQuery, PayrollQueryQueryVariables>;
export const CreateRevenueRecordMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateRevenueRecordMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"CreateRevenueRecordInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createRevenueRecord"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"revenueRecord"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"totalRevenue"}},{"kind":"Field","name":{"kind":"Name","value":"totalProfit"}},{"kind":"Field","name":{"kind":"Name","value":"reconciled"}},{"kind":"Field","name":{"kind":"Name","value":"source"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"field"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]}}]}}]} as unknown as DocumentNode<CreateRevenueRecordMutationMutation, CreateRevenueRecordMutationMutationVariables>;
export const GroupedRevenueRecordsQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GroupedRevenueRecordsQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"pagination"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"PaginationInput"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"driverId"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"groupedRevenueRecords"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"pagination"},"value":{"kind":"Variable","name":{"kind":"Name","value":"pagination"}}},{"kind":"Argument","name":{"kind":"Name","value":"driverId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"driverId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"driverId"}},{"kind":"Field","name":{"kind":"Name","value":"driverName"}},{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"totalRevenue"}},{"kind":"Field","name":{"kind":"Name","value":"totalProfit"}},{"kind":"Field","name":{"kind":"Name","value":"allReconciled"}},{"kind":"Field","name":{"kind":"Name","value":"revenueCount"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleName"}},{"kind":"Field","name":{"kind":"Name","value":"sourceBreakdown"}},{"kind":"Field","name":{"kind":"Name","value":"revenueRecords"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"totalRevenue"}},{"kind":"Field","name":{"kind":"Name","value":"totalProfit"}},{"kind":"Field","name":{"kind":"Name","value":"reconciled"}},{"kind":"Field","name":{"kind":"Name","value":"source"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"pagination"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentPage"}},{"kind":"Field","name":{"kind":"Name","value":"firstPage"}},{"kind":"Field","name":{"kind":"Name","value":"lastPage"}},{"kind":"Field","name":{"kind":"Name","value":"nextPage"}},{"kind":"Field","name":{"kind":"Name","value":"pageCount"}},{"kind":"Field","name":{"kind":"Name","value":"pageSize"}},{"kind":"Field","name":{"kind":"Name","value":"prevPage"}},{"kind":"Field","name":{"kind":"Name","value":"totalSize"}}]}},{"kind":"Field","name":{"kind":"Name","value":"totalRevenue"}},{"kind":"Field","name":{"kind":"Name","value":"totalProfit"}},{"kind":"Field","name":{"kind":"Name","value":"sourceTotals"}}]}}]}}]} as unknown as DocumentNode<GroupedRevenueRecordsQueryQuery, GroupedRevenueRecordsQueryQueryVariables>;
export const RevenueRecordsQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RevenueRecordsQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601Date"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"revenueRecords"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"totalRevenue"}},{"kind":"Field","name":{"kind":"Name","value":"totalProfit"}},{"kind":"Field","name":{"kind":"Name","value":"reconciled"}},{"kind":"Field","name":{"kind":"Name","value":"source"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}},{"kind":"Field","name":{"kind":"Name","value":"city"}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}}]}}]}}]}}]} as unknown as DocumentNode<RevenueRecordsQueryQuery, RevenueRecordsQueryQueryVariables>;
export const UpdateRevenueRecordMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpdateRevenueRecordMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"revenueRecordId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"reconciled"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Boolean"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateRevenueRecord"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"revenueRecordId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"revenueRecordId"}}},{"kind":"Argument","name":{"kind":"Name","value":"reconciled"},"value":{"kind":"Variable","name":{"kind":"Name","value":"reconciled"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"revenueRecord"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"totalRevenue"}},{"kind":"Field","name":{"kind":"Name","value":"totalProfit"}},{"kind":"Field","name":{"kind":"Name","value":"reconciled"}},{"kind":"Field","name":{"kind":"Name","value":"source"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"field"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]}}]}}]} as unknown as DocumentNode<UpdateRevenueRecordMutationMutation, UpdateRevenueRecordMutationMutationVariables>;
export const PauseShiftMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"PauseShiftMutation"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"pauseShift"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"shiftEvent"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"eventType"}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"model"}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"field"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]}}]}}]} as unknown as DocumentNode<PauseShiftMutationMutation, PauseShiftMutationMutationVariables>;
export const ResumeShiftMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ResumeShiftMutation"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"resumeShift"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"shiftEvent"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"eventType"}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"model"}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"field"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]}}]}}]} as unknown as DocumentNode<ResumeShiftMutationMutation, ResumeShiftMutationMutationVariables>;
export const TodayShiftsQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"TodayShiftsQuery"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"todayShifts"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"city"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"actualStartTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}},{"kind":"Field","name":{"kind":"Name","value":"actualEndTime"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"phoneNumber"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"model"}},{"kind":"Field","name":{"kind":"Name","value":"make"}},{"kind":"Field","name":{"kind":"Name","value":"yearOfManufacture"}},{"kind":"Field","name":{"kind":"Name","value":"latestOdometer"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}},{"kind":"Field","name":{"kind":"Name","value":"latestRange"}},{"kind":"Field","name":{"kind":"Name","value":"telematicsSource"}}]}},{"kind":"Field","name":{"kind":"Name","value":"shiftEvents"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"eventType"}},{"kind":"Field","name":{"kind":"Name","value":"odometer"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleRange"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLat"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLon"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}},{"kind":"Field","name":{"kind":"Name","value":"revenueRecords"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"totalRevenue"}},{"kind":"Field","name":{"kind":"Name","value":"totalProfit"}},{"kind":"Field","name":{"kind":"Name","value":"reconciled"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]}}]} as unknown as DocumentNode<TodayShiftsQueryQuery, TodayShiftsQueryQueryVariables>;
export const TodaysShiftEventsQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"TodaysShiftEventsQuery"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"todaysShiftEvents"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"eventType"}},{"kind":"Field","name":{"kind":"Name","value":"odometer"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleRange"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLat"}},{"kind":"Field","name":{"kind":"Name","value":"gpsLon"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"shiftAssignment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"driver"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}}]}}]}}]}}]}}]} as unknown as DocumentNode<TodaysShiftEventsQueryQuery, TodaysShiftEventsQueryQueryVariables>;
export const UpdateVehicleMutationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpdateVehicleMutation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UpdateVehicleInput"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"vehicleId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateVehicle"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}},{"kind":"Argument","name":{"kind":"Name","value":"vehicleId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"vehicleId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"vehicle"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"VehicleFragment"}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"field"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"VehicleFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Vehicle"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"globalId"}},{"kind":"Field","name":{"kind":"Name","value":"make"}},{"kind":"Field","name":{"kind":"Name","value":"model"}},{"kind":"Field","name":{"kind":"Name","value":"licensePlate"}},{"kind":"Field","name":{"kind":"Name","value":"yearOfManufacture"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}},{"kind":"Field","name":{"kind":"Name","value":"latestOdometer"}},{"kind":"Field","name":{"kind":"Name","value":"latestRange"}},{"kind":"Field","name":{"kind":"Name","value":"telematicsSource"}},{"kind":"Field","name":{"kind":"Name","value":"vehicleImageUrl"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"inUse"}}]}}]} as unknown as DocumentNode<UpdateVehicleMutationMutation, UpdateVehicleMutationMutationVariables>;