mutation ClockOutMutation($input: ClockOutInput!) {
  clockOut(input: $input) {
    shiftEvent {
      id
      eventType
      odometer
      vehicleRange
      gpsLat
      gpsLon
      notes
      shiftAssignment {
        id
        status
        driver {
          id
          fullName
        }
        vehicle {
          id
          licensePlate
          model
        }
      }
    }
    errors {
      message
      field
      code
    }
  }
}
