query CurrentUserQuery {
  currentUser {
    id
    globalId
    email
    firstName
    lastName
    fullName
    createdAt
    updatedAt
    signInCount
    permissions {
      id
      slug
    }
    driver {
      id
      fullName
    }
  }
}
