mutation DeclineScheduledTripMutation($token: String!) {
  declineScheduledTrip(token: $token) {
    scheduledTrip {
      id
      state
      clientName
      pickupDatetime
    }
    errors {
      message
      field
      code
    }
  }
}
